
version: '3'

services:

    # web server
    # https://hub.docker.com/_/nginx
    web-server:
        container_name: ${SERVER_CONTAINER_NAME}
        image: nginx:latest
        volumes:
            - './nginx:/etc/nginx/templates'
            - './src:${APP_ROOT}'
        ports:
            - '${APP_PORT}:80'
        environment:
            - PHP_CONTAINER_NAME=${PHP_CONTAINER_NAME}
            - SERVER_PORT=${APP_PORT}
            - SERVER_NAME=${HOSTNAME}
            - DOCUMENT_ROOT=${DOCUMENT_ROOT}
        networks:
            - project-network

    # php
    # https://hub.docker.com/_/php
    php-processor:
        container_name: ${PHP_CONTAINER_NAME}
        build: ./php
        volumes:
            - './src:${APP_ROOT}'
        networks:
            - project-network

    # db
    # https://hub.docker.com/_/mysql
    database:
        container_name: ${DATABASE_CONTAINER_NAME}
        image: mysql
        volumes:
            - './mysql:${DB_PATH}'
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
        networks:
            - project-network

    # db admin
    # https://hub.docker.com/_/adminer
    database-admin:
        container_name: ${DB_ADMIN_CONTAINER_NAME}
        image: adminer
        ports:
            - ${DB_ADMIN_PORT}:8080
        networks:
            - project-network

networks:
    project-network:
